# Generated by Django 5.2.3 on 2025-08-12 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, unique=True)),
                ('index_all_items', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('FOOD', 'Food'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport'), ('HEALTH', 'Health'), ('MISC', 'Misc')], max_length=20)),
                ('amount_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_status', models.CharField(choices=[('SINGLE', 'Single'), ('MFJ', 'Married Filing Jointly'), ('MFS', 'Married Filing Separately'), ('HOH', 'Head of Household')], default='SINGLE', max_length=10)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('income_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('from_state', models.CharField(default='MA', max_length=2)),
                ('target_state', models.CharField(default='ME', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
