# Generated by Django 5.2.3 on 2025-08-19 13:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_name', models.CharField(help_text='Name for this calculation scenario', max_length=100)),
                ('current_rent', models.DecimalField(decimal_places=2, help_text='Current monthly rent/mortgage payment', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_utilities', models.DecimalField(decimal_places=2, help_text='Current monthly utilities cost', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_groceries', models.DecimalField(decimal_places=2, help_text='Current monthly grocery expenses', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_transportation', models.DecimalField(decimal_places=2, help_text='Current monthly transportation costs', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_healthcare', models.DecimalField(decimal_places=2, help_text='Current monthly healthcare expenses', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_entertainment', models.DecimalField(decimal_places=2, help_text='Current monthly entertainment/dining expenses', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_annual_income', models.DecimalField(decimal_places=2, help_text='Gross annual income', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('military_retirement_income', models.DecimalField(decimal_places=2, default=0, help_text='Annual military retirement income', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('disability_compensation_income', models.DecimalField(decimal_places=2, default=0, help_text='Annual VA disability compensation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_maine_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_maine_utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_maine_groceries', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_maine_transportation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('origin_state_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maine_state_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_monthly_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly savings (negative means increase in costs)', max_digits=10, null=True)),
                ('total_annual_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated annual savings', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('destination_state', models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, related_name='destination_calculations', to='state_data.statedata')),
                ('origin_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_calculations', to='state_data.statedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Calculation',
                'verbose_name_plural': 'Cost Calculations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='calculations.costcalculation')),
            ],
            options={
                'verbose_name': 'Calculation Note',
                'verbose_name_plural': 'Calculation Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_veteran', models.BooleanField(default=True)),
                ('service_branch', models.CharField(blank=True, choices=[('army', 'Army'), ('navy', 'Navy'), ('air_force', 'Air Force'), ('marines', 'Marines'), ('coast_guard', 'Coast Guard'), ('space_force', 'Space Force')], max_length=20)),
                ('receives_disability_compensation', models.BooleanField(default=False)),
                ('disability_rating', models.IntegerField(blank=True, help_text='VA disability rating percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('receives_military_retirement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_residents', to='state_data.statedata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
