# Generated by Django 5.2.3 on 2025-08-20 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
        ('state_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcalculation',
            name='destination_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_calculations', to='state_data.statedata'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disability_rating',
            field=models.IntegerField(blank=True, help_text='VA disability rating percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
